.circleci/config.yml
docs/conf.py
setup.py
sphinx_notebook/__init__.py
sphinx_notebook/parser.py

This is an attempt at fixing ipywidgets following the suggestions of @akhmerov...for some reason it still doesn't work though :-/

fixing ipywidgets

---

setup.py

I realized that the install wasn't working on circle because the `setup.py` was importing the module in order to pull the latest version, and this was causing it to fail because necessary packages weren't installed. This fixes that by manually parsing the file and pulling out the version.

fixing install w/o prior installs

---

.circleci/config.yml
docs/jupyter_sphinx.md
myst_nb/__init__.py
myst_nb/_static/mystnb.css
setup.py

This adds a few reasonable CSS rules for notebook outputs, and also adds an "execute" directive that we can start to use for the notebook representation of the MyST markdown file

Updates to CSS and directive

---

docs/notebooks.ipynb
myst_nb/parser.py

Because the myst-parser will parse a line as a paragraph if it's a one-liner, this adds a newline to make sure it's parsed as a heading if need be

fixing parser by adding newline

---

docs/conf.py
docs/index.md
myst_nb/parser.py

This uses `Document` instead of tokenize, per @chrisjsewell 's latest comments about improvements to that class.
It also adds a simple try/except block to capture any errors associated with parsing the notebook and display a message that includes the notebook cell and path. @chrisjsewell do you think this is a reasonable way to handle this? Know of a better way to get the error message to display? I know it's not idea because the errors won't propagate past this step in Sphinx, but as a stopgap is it the right improvement?

using document and adding a more helpful error

---

myst_nb/nb_glue/domain.py
tests/notebooks/with_glue.ipynb

closes #78 you can't use `glue`, as they have to be under the same domain, but you can use `glu:`
@jstac @choldgraf

Add `glu:` alternative to `glue:any`

---

docs/index.md

What @phaustin should have actually done in #92 lol (because it is now in the `rtd` extra)

DOCS: Remove extra pydata theme install

---

docs/use/basic.ipynb

@jstac from the discussion here https://github.com/ExecutableBookProject/meta/issues/45
I don't think the changed python version in the metadata will be a problem but I can revert it to 3.8.0 if you like and update this PR

Add equation example to basic.ipynb example jupyter notebook

---

myst_nb/transform.py

This just adds another key to the render priority in case somebody is building `singlehtml`. It doesn't change functionality at all

Adding singlehtml key to render priority

---

docs/use/glue.ipynb

Just a minor typo (I think) that I stumbled across while working my way through these docs. MyST-NB looks like it has some really nice features!

DOC: Fixed typo in subsection heading

---

docs/develop/contributing.md

@choldgraf @chrisjsewell, have added a few lines on unit testing. What do you think about this? Should I make it more/less verbose? Should I also write about using `mock_document`, `MockEnv`?

Documentation for unit testing

---

setup.py

I missed the `setup.py` package update, this makes sure that anything inside `_static` gets packaged w/ myst-nb

packaging js with install

---

myst_nb/_static/mystnb.css

Two main changes:
* Adds whitespace above the cell outputs (and closes https://github.com/ExecutableBookProject/quantecon-example/issues/5)
* Makes pandas dataframes snap to the left instead of being centered (which is in-line with how we treat all other outputs)
old: 
new:
(forgive the left margins, those haven't changed it's just a matter of where I took the screenshot)
example: https://354-241268229-gh.circle-artifacts.com/0/html/use/glue.html
@jstac what do you think?

output cell tweaks

---

.coveragerc
.github/workflows/tests.yml
setup.py
tests/notebooks/complex_outputs.ipynb
tests/notebooks/complex_outputs_unrun.ipynb
tests/test_execute/test_complex_outputs_unrun.ipynb
tests/test_execute/test_complex_outputs_unrun.xml
tests/test_execute/test_complex_outputs_unrun_nbclient.ipynb
tests/test_execute/test_complex_outputs_unrun_nbclient.xml
tests/test_parser/test_complex_outputs.xml
tests/test_transform/test_complex_outputs.xml

Coveralls doesn't support GitHub actions properly for forked PRs 😒 coverallsapp/github-action#30
https://github.com/codecov/codecov-action

Move to codecov

---

myst_nb/cache.py

Checking if the extension is `ipynb` before assuming it is a notebook and reading the cells for outputs.

checking extension before reading to check outputs

---

docs/use/glue.md
docs/use/hiding.md
docs/use/markdown.md
myst_nb/__init__.py
myst_nb/parser.py

This updates our tags behavior so that it allows for hyphenated versions as well as underscores (ideally we'd totally switch but I'm keeping underscores for legacy support). So now:
`hide_input` -> `hide-input`
and so on.
This is more in-line with other jupyter tagging conventions such as `raises-exception`.
None of the actual behavior should change...here's the page where we describe this for reference:
https://385-241268229-gh.circle-artifacts.com/0/html/use/hiding.html
it should be no different than
https://myst-nb.readthedocs.io/en/latest/use/hiding.html

tags use hyphens now

---

myst_nb/parser.py
tests/test_parser.py
tests/test_text_based.py

I *think* that this is the only thing that we need to do in order to get nested metadata working.
edit: I think I need to edit some of the tests because the metadata in the output document will be different...I will try and figure out to update the regressions stuff so that it works (though somebody comment if that's not the problem here). @chrisjsewell are we OK with just updating the regression templates so that they now include the JSON-serialized nested metadata?
closes #147

serializing nested ntbk metadata items

---

myst_nb/cache.py

This is a bug that is difficult to reproduce because it only happens when you build the documentation from a folder that is not strictly in the parent tree of the build folder. By that I mean a folder structure like this:
This works:
```
run/build/from/this/folder/path/to/docs
run/build/from/this/folder
```
This raises an error:
```
run/build/from/this/folder/path/to/docs
run/build/from/this/other/folder
```
The problem is in Pathlib somewhere when it is calling `relative_to`. This method only works if the two items share the same root, which isn't true in the second case above. So this PR just uses relpath.

fixing relpath bug

---

.github/workflows/tests.yml

I found that we have duplicate tests running because our github action runs on both pull_request and push. I believe that this configuration will make it run only once for forked pull requests so we don't duplicate test jobs

github action conditions

---

myst_nb/parser.py
myst_nb/transform.py
tests/test_transform.py
tests/test_transform/test_complex_outputs_latex.xml

Added a copy method which also takes `outputs` as argument
fixes https://github.com/ExecutableBookProject/MyST-NB/issues/151

Added a copy method to celloutputbundlenode

---

myst_nb/_static/mystnb.css

This removes the max height restriction for images that are `glue-pasted` into tables, so they aren't too tiny.
Current:
Updated:
It's not a huge difference but at least enough that @martinagvilas noticed 😄

inline images in tables size

---

docs/use/markdown.md
myst_nb/__init__.py
tests/notebooks/basic_nometadata.md
tests/test_text_based.py

This adds a code cell directive that simply raises a warning about the code cell, and then returns nothing (so the content won't make it into the final page). I thought about making it parse the content as "literal" but for now it seemed reasonable to just raise the warning and make it "obvious" that there was an error in the end-product, which I think will increase the likelihood that people look through the logs for errors.
Also cleaned up the "myst markdown notebooks" section a little bit
What do folks think?
closes https://github.com/executablebooks/MyST-NB/issues/182

adding code cell directive for warning

---

docs/conf.py
docs/index.md
myst_nb/cache.py
tests/notebooks/basic_relative.ipynb
tests/test_execute.py

This adds the `cwd` command to our call to `nbclient.execute`, and also updates a test to use a relative file path in the code to make sure it works
fixes #180

executing notebooks w/ nbclient in their directory

---

docs/conf.py
docs/examples/interactive.md

we were hardcoding a mimetype output, but I think instead we should just use the default renderer, which plotly tries to choose based on the execution environment. I think this will lead to more consistent behavior

fixing plotly

---

myst_nb/cache.py
myst_nb/converter.py
myst_nb/nb_glue/domain.py
myst_nb/nb_glue/utils.py
setup.py
tests/conftest.py
tests/notebooks/basic_relative.ipynb

see https://github.com/executablebooks/jupyter-book/pull/719

fix windows utf8 encoding  part 3/3

---

docs/conf.py
docs/index.md
docs/use/index.md
docs/use/markdown.md
docs/use/myst.md
docs/use/start.md

This is an attempt at clarifying a few things that were getting intermixed in our documentation, to try and resolve some conceptual issues that arose in #210 . It does the following:
* Creates a top-level page about MyST Markdown Notebooks, with links to other relevant documentation
* Adds more information about MyST Notebooks like the "spec" for a minimal MyST Notebook, with lots of cross-refs to other documentation for how to use MyST Notebooks in other tools
* Re-focuses the `Use and Configure` section to explicitly be about the Sphinx extension.

adding more explanation of myst notebooks

---

myst_nb/__init__.py
myst_nb/exec_table.py
myst_nb/execution.py
myst_nb/parser.py
tests/nb_fixtures/basic.txt
tests/test_execute.py
tests/test_text_based.py
tests/test_text_based/test_basic_run_exec_off.xml
tox.ini

Also
- Use custom `SphinxError` for invalid configuration values
- fixed bug when code cell language of failed notebooks was being added as None
- Sort table rows by docname

🐛 FIX: Update of `nb-exec-table`s

---

myst_nb/_static/mystnb.css

This suggestion fixes the issue with Jupyter Book that I raised last week, which was that the toolbars for Bokeh data visualizations are not showing up. Removing cell backgrounds as none allows them to show up correctly.
https://github.com/executablebooks/jupyter-book/issues/905

🐛 FIX: remove cell background as none

---

myst_nb/_static/mystnb.css

This is related to my previous pull request #261 and previous Jupyter Book issue executablebooks/jupyter-book#905, which was that Bokeh plot toolbars were not showing up. My previous pull request fixed the toolbar issue, but I subsequently realized that Bokeh hover tooltips were showing up with transparent backgrounds, which is not how they should appear.
Removing the cell background-color entirely fixes the issue with Bokeh hover tooltips, and it doesn't seem like this fix is causing any other problems with the cells in my personal Jupyter Book.
Bokeh plot with cell background-color as `transparent`
Bokeh plot with cell background-color removed

🐛 FIX: remove cell background-color CSS for cells

---

CHANGELOG.md
myst_nb/__init__.py

This release adds an experimental MyST-NB feature to enable loading of code from a file
for `code-cell` directives using a `:load: <file>` option.
Usage information is available in the [docs](https://myst-nb.readthedocs.io/en/latest/use/markdown.html#syntax-for-code-cells)

🚀 RELEASE: v0.12.0

---

setup.py
tests/test_text_based.py

Also pinned a few other package versions required for tests to pass.
I want this because `jupyter_sphinx 0.13.2` gets rid of the `"Notebook code has no file extension metadata"` warning that occasionally breaks my builds, and the pip dependency resolver complains if I try to install 0.13.2 with myst-nb.
I know how to work around that warning by adding appropriate metadata to the notebooks, but it's annoying to have to do that for every new notebook, and it's extra boilerplate that shouldn't be necessary.

⬆️ UPDATE: jupyter_sphinx

---

.github/workflows/tests.yml
myst_nb/render_outputs.py
setup.cfg
tests/conftest.py
tests/test_render_outputs.py
tox.ini

- Use new entry point loading interface.
- `sphinx.testing.path.Path.text()` -> `sphinx.testing.path.Path.read_text()`
- Add python 3.9 to test matrix

👌 IMPROVE: Fix test warnings

---

README.md
myst_nb/render_outputs.py
setup.cfg

Despite pinning to `importlib-metdata>=3.6` in #319,
https://github.com/python/importlib_metadata/issues/308
could still cause Conda installs to fail using the new entry points interface.
So now the pinning is removed, and the new interface is only used if available.

👌 IMPROVE: Support old entry points interface

---

.pre-commit-config.yaml
docs/examples/custom-formats.Rmd
myst_nb/__init__.py
myst_nb/parser.py
setup.cfg
tests/test_mystnb_features.py
tests/test_parser.py
tests/test_text_based.py

Updated via dependencies which support this version;
- myst-parser -> 0.14.0
- jupytext -> 1.11.2
See https://github.com/executablebooks/markdown-it-py/blob/master/CHANGELOG.md
and https://github.com/executablebooks/MyST-Parser/blob/master/CHANGELOG.md
Also added mypy type checking for the parser code.

⬆️ UPGRADE: markdown-it-py v1.0

---

setup.cfg

- fixes #325 
- with the least work possible
- could expand test matrix to test vs `5.x` and `6.x`

⬆️ UPGRADE: nbconvert 6 support

---

myst_nb/execution.py

fixes #327 
Allows more complex suffixes in `env.nb_allowed_exec_suffixes`

Allows more complex suffixes in notebooks

---

docs/conf.py
setup.cfg

🔧 MAINT: Pin ipykernel to ~v5.5

---

myst_nb/_static/mystnb.css

closes #287 
The original problem was that wildcard CSS leaks, and it's hard to override. Unfortunately, it isn't completely clear to me what the wildcard was supposed to catch in the first place (the description in the source was vague and #287 lacked this info). To figure it out I removed the wildcard and compared the outputs, taking the jupyterbook repo. The proposed change seems to fix the problem with preformatted outputs.
Without wildcard:
With the proposed change:
Identical to the original, as far as I can tell. If I overlooked other problems, do let me know.

🔧 MAINT: Make a more specific selector for no-border

---

CHANGELOG.md

This PR makes updates in preparation for v0.13 release
The `myst_nb/__init__.py` file is already updated to `0.13`
@chrisjsewell I made the update to `0.13` (rather than a minor release) in similar style to `myst_parser` when it updated to support `sphinx v4`.

🚀 RELEASE: Updates for v0.13 release

---

docs/use/start.md
myst_nb/__init__.py
myst_nb/render_outputs.py
tests/notebooks/merge_streams.ipynb
tests/test_render_outputs.py
tests/test_render_outputs/test_merge_streams.xml
tox.ini

If `True`, ensure all stdout / stderr output streams are merged into single outputs.
This ensures deterministic outputs.

✨ NEW: `nb_merge_streams` configuration

---

myst_nb/_static/mystnb.css

This pull request adds support for 8-bit ANSI colours, as discussed in #378.
I got the ANSI to RGB mappings from [this repository](https://github.com/marionebl/ansi-to-rgb) and converted them into a JSON file.
I then wrote the following script to create the style definitions with hex colour codes:
```
with open('ansi-to-rgb.json') as file:
rgb = json.load(file)
for ansi, rgb in rgb.items():
N = int(ansi)
HEX = f'#{rgb[0]:02x}{rgb[1]:02x}{rgb[2]:02x}'.upper()
print(f'div.highlight .-Color[class*=-C{N}] \u007b\n  color: {HEX} \n\u007d')
print(f'div.highlight .-Color[class*=-BGC{N}] \u007b\n  background-color: {HEX} \n\u007d')
```
Test results:
```
============================================ test session starts ============================================
platform darwin -- Python 3.9.9, …
```

 👌 IMPROVE: Add CSS support for 8-bit ANSI colours

---

setup.cfg

ipython v8 is only available for Python 3.8+, and it changes exception text, which fails some regression tests

🧪 TESTS: Pin ipython<8

---

CHANGELOG.md
docs/changelog.md
docs/index.md
myst_nb/__init__.py

This release brings in a few minor feature improvements. The biggest change is that the toggle button CSS now behaves a bit more sensibly, and doesn't jut out to the right into the margin of the page.
supercedes #https://github.com/executablebooks/MyST-NB/pull/369

🚀 RELEASE: v0.13.2

---

.github/workflows/tests.yml
docs/use/glue.md
myst_nb/core/render.py
myst_nb/glue/directives.py
myst_nb/glue/utils.py

`glue:figure` directive options:
| Option | Type | Description |
| ------ | ---- | ----------- |
| alt | text | Alternate text of an image |
| height | length | The desired height of an image |
| width | length or percentage | The width of an image |
| scale | percentage | The uniform scaling factor of an image |
| class | text | A space-separated list of class names for the image |
| figwidth | length or percentage | The width of the figure |
| figclass | text | A space-separated list of class names for the figure |
| name | text | referenceable label for the figure |

👌 IMPROVE: Add image options to `glue:figure`

---

docs/use/execute.md
myst_nb/core/config.py
myst_nb/core/execute.py
pyproject.toml
tests/test_execute.py
tests/test_execute/test_allow_errors_auto.ipynb
tests/test_execute/test_allow_errors_auto.xml
tests/test_execute/test_allow_errors_cache.ipynb
tests/test_execute/test_allow_errors_cache.xml
tests/test_execute/test_basic_failing_auto.ipynb
tests/test_execute/test_basic_failing_auto.xml
tests/test_execute/test_basic_failing_cache.ipynb
tests/test_execute/test_basic_failing_cache.xml
tox.ini

✨ NEW: Add `nb_execution_raise_on_error` config

---

docs/render/interactive.md
pyproject.toml

This was unintentionally removed,
since it was previously pulled in via another dependency.

🔧 MAINTAIN: Re-add ipykernel as dependency

---

myst_nb/core/execute/base.py
myst_nb/core/execute/inline.py
myst_nb/core/variables.py
myst_nb/docutils_.py
myst_nb/ext/eval/__init__.py
myst_nb/ext/glue/directives.py
myst_nb/ext/glue/roles.py

Previously, it was assumed that a variable evaluation would only ever create 0 or 1 outputs.
Multiple are now allowed.
Also, error messages are appended with the output index.
closes #436

🐛 FIX: Inline exec variables with multiple outputs

---

docs/render/hiding.md
myst_nb/core/config.py
myst_nb/core/render.py
myst_nb/sphinx_.py
myst_nb/sphinx_ext.py
myst_nb/static/mystnb.css
pyproject.toml
tests/notebooks/hide_cell_content.ipynb
tests/test_render_outputs.py
tests/test_render_outputs/test_hide_cell_content.xml
tox.ini

This allows for tighter integration with myst-nb:
- Nicer rendering of the hidden content
- Customisation of the hide/show prompts
The implementation uses "static" details/summary HTML tags directly + CSS,
similar to [sphinx-design](https://github.com/executablebooks/sphinx-design),
rather than the JS implementation used by sphinx-togglebutton.

👌 IMPROVE: Replace sphinx-togglebutton with built-in functionality

---

myst_nb/static/mystnb.css

👌 IMPROVE: Move CSS colors to variables

---

docs/render/hiding.md
myst_nb/core/render.py
myst_nb/sphinx_.py
myst_nb/static/mystnb.css
tests/test_render_outputs/test_hide_cell_content.xml

It now uses the same margin color as the cell source and, when the cell source is present,
is "connected" to that, to form a single element.

👌 IMPROVE: `hide-output` button

---

docs/quickstart.md

sphinx projects are often in the "docs folder",
and also the later part of the quick start makes this assumption:
https://myst-nb.readthedocs.io/en/latest/quickstart.html

Update quickstart.md to include docs folder

---

pyproject.toml

A cryptic error message during our docs build is fixed in newer versions of `sphinx-design`. This PR just bumps that RTD dependency.

docs: update to latest `sphinx-design`

---

docs/conf.py

Widgets in the docs stopped rendering in https://myst-nb.readthedocs.io/en/latest/render/interactive.html#ipywidgets. Trying out the fix suggested in #458 to see if it fixes the issue.

Add ipywidgets javascript

---

docs/render/hiding.md
docs/render/interactive.md
myst_nb/core/config.py

Should fix #458, supercedes https://github.com/executablebooks/MyST-NB/pull/469

fix: use jsdelivr CDN for ipywidgets

---

pyproject.toml

Bumping jupyter cache versions

UPDATE: jupyter-cache v0.6.0

---

docs/quickstart.md
docs/render/hiding.md

I experienced this error, but I found a solution.
This is a hint how to fix it.

DOCS: Hint to avoid Extension error in sphinx-build

---

CHANGELOG.md
myst_nb/__init__.py

A patch release to support a few more versions

RLS: v0.17.2

---

.github/workflows/tests.yml
pyproject.toml
tox.ini

This PR removes `python==3.7` from the test suites and list of supported python versions. 
https://devguide.python.org/versions/
The deprecation date for `3.7` is coming up in June 2023.

MAINT: remove python=3.7 as EOL is June 2023

---

myst_nb/core/config.py
myst_nb/core/execute/base.py
myst_nb/core/execute/inline.py
myst_nb/ext/eval/__init__.py

Currently, the `eval` role and directives *only* allow for C-like identifiers.
Remove the restriction on expression values in `eval` contexts.
- Users are discouraged from writing unreadably complex code that breaks the narrative flow.
- Users are discouraged from writing code that can have side-effects (as there are far fewer rich-display hook implementations than there are user functions that modify globals).
- Non-"pure" functions would lead to different results when executing the notebook in environments that do not support expression execution, e.g. `jupyter-cache` or `Jupyter Lab`[^myst-note].
- Every language has a different notion of "identifier". We're exclusively permitting C-like identifiers only. The current REGEX actually doesn't support certain valid Python identifiers that …

Feat: allow any value for expr

---

.github/workflows/tests.yml
pyproject.toml

There is a dependency hell to resolve here due to the testing requirements. However this package is a blocking requirement for various other packages downstream. These test requirements should be addressed.
See my fork's PR for current status https://github.com/LecrisUT/MyST-NB/pull/1

Support sphinx 7

---

myst_nb/core/execute/cache.py

When
```python
nb_execution_raise_on_error = True
nb_execution_show_tb = True
```
the traceback is not showed, which is very inconvenient when it happens during a CI job!
I guess it is only an issue of incompatibility between these two options, which should be fixed by this swap.
Does it make sense?

Show traceback before raising ExecutionError

---

.pre-commit-config.yaml
docs/reference/contributing.md
docs/render/glue.md
myst_nb/core/render.py
myst_nb/sphinx_.py

Typos found via `codespell -S *.ipynb` and `typos --format brief`.

📚 DOCS: Fix typos and add codespell pre-commit hook

---

tests/conftest.py

Hi,
This PR should fix the failing CI for sphinx 7 which adds translation metadata to some of the outputs.
I've patched the file_regression comparison fixture to strip out the differences between sphinx<7 and 7. Hopefully this will allow the merge of #532 #533 and #534 and is maybe enough for a new release as requested in #530.
Thanks!

Patch file_regression fixture for sphinx backwards compatibility

---

myst_nb/core/execute/inline.py
tests/conftest.py
tests/test_cli.py
tests/test_codecell_file.py
tests/test_eval.py
tests/test_execute.py
tests/test_glue.py
tests/test_parser.py
tests/test_render_outputs.py
tests/test_text_based.py

This PR fixes an instance where a `myst-nb` test fixture was using a test fixture that was previously provided by sphinx but was removed sometime between the release of `6.2.1` and `7.2.6`. Closes #545. This should also unblock a new release.
- Swapped out the `tempdir` fixture for `pytest`'s `tmpdir` fixture as a drop-in replacement.

[Doc] Fix broken pytest fixture

---

.pre-commit-config.yaml
docs/reference/contributing.md
myst_nb/core/config.py
myst_nb/core/render.py
myst_nb/docutils_.py
myst_nb/sphinx_.py
myst_nb/sphinx_ext.py
pyproject.toml
tox.ini

This PR replaces flake8 with ruff, updates some linting defaults, and fixes mypy.

MAINT: update linting

---

.readthedocs.yml

The configuration file
```
python:
version: "3.8"
```
syntax [has been deprecated](https://docs.readthedocs.io/en/stable/config-file/v2.html#python) by readthedocs.
Instead,
```
uild:
os: ubuntu-22.04
tools:
python: "3.11"
```
has to be used. This would fix test errors caused by the readthedocs build (eg. here: https://github.com/executablebooks/MyST-NB/pull/553).

Update readthedocs Config File to fix Test Error

---

.github/workflows/tests.yml
pyproject.toml
tox.ini

We should try and support SPEC 0, which will keep our development burden down. As such, this PR drops 3.8

maint: bump minimum Python version

---

myst_nb/docutils_.py
myst_nb/ext/execution_tables.py
pyproject.toml
tests/conftest.py
tests/test_execute/test_complex_outputs_unrun_auto.xml
tests/test_execute/test_complex_outputs_unrun_cache.xml
tests/test_execute/test_custom_convert_auto.xml
tests/test_execute/test_custom_convert_cache.xml

This deprecation was introduced in docutils 0.18.2
This PR also updates deprecated usage of `importlib.resources`, and updates & pins the pandas regression tests.

maint: use `findall` instead of `traverse`

---

docs/configuration.md

Hello,
Just to mention that there is an extra comma in this example that makes this JSON invalid :-)

fix(docs): extra comma forgotten

---

.github/workflows/tests.yml
.pre-commit-config.yaml
myst_nb/sphinx_ext.py

MAINT: appease mypy

---

docs/render/glue.md

For now this fixes our docs. We should develop some guidance on this for users.

DOCS: set printoptions to disable modern scalar printing

---

.github/workflows/tests.yml
myst_nb/core/read.py
tox.ini

It's beyond the scope for this PR, but I would also suggest adding a job that pulls the development versions of dependencies, even if it's just in a job that runs from a e.g. weekly cron; so end users would not run into incompatibilities when an upstream release is out.
(We do this for sphinx extensions and pytest plugins; as well as for libraries that more and more test against nightly wheels; and it's really nice from the release manager perspective as it removes a lot of cases for a rushed compatibility release). 
Closes #619

MAINT: fix sphinx 8.0 compatibility

---

.pre-commit-config.yaml

When maintainer capacity is limited on a low-traffic repo, there is no need for the noise from the automated weekly PRs

MAINT: only doing monthly pre-commit update

---

docs/render/glue.md

As discussed in #610, changes in NumPy 2.0 for `text/plain` representation of numbers means that we need an adjustment to either NumPy's print options or how glueing is done. This docs update should address those changes while potential adjustments are sorted out upstream.
Closes #610
Screenshot on a locally built page

Update glueing docs for NumPy >=2.0

---

CHANGELOG.md

copying over the release notes

DOCS: adding changelog for 1.1.2

---

.github/workflows/tests.yml
pyproject.toml
tox.ini

I see failing tests locally, but some of those are failing with other python versions, too, so I'll use the CI here to check for actual issues.

MAINT: adding python 3.13 to CI and classifiers

---

.github/workflows/tests.yml
.github/workflows/tests_devdeps.yml
tox.ini

Some cleanup and enhancement to the CI.
I choose to not run the devdeps job on PRs so e.g. new sphinx incompatibilities won't create failing CI status for them. However, test will run weekly on master, so incompatibilities can be picked up.
I included testing only with myst-parser and sphinx dev versions, but the job can be extended to include other dependencies.

CI: adding devdeps testing and cron and workflow dispatch

---

.github/workflows/tests.yml
myst_nb/core/read.py
pyproject.toml

TST: fail on warnings

---

.readthedocs.yml

When opening https://github.com/executablebooks/MyST-NB/pull/656, the [build failed](https://readthedocs.org/projects/myst-nb/builds/27027868/) because [an explicit configuration key is now required](https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/)
so anyway here's that

add `configuration` key to readthedocs.yml

---

.github/workflows/tests.yml

I use this PR for fixing up CI to a point that we can tag a release. Incremental commits are expected as I iterate over the test matrix.

MAINT: fix CI in prep for release

---

docs/render/format_code_cells.md
myst_nb/core/config.py

This PR make a minor documentation adjustment to inform that the `merge_streams` configuration option separately merges `stdout` and `stderr`, resolving issue #664.  The previous wording, while technically correct, seemed to imply that `stdout` and `stderr` streams will be merged together.
Note: There are some testing issues, and code formatting issues with `black` and `ruff` that I did not fix to keep this PR minimal.  Let me know if you would like me to include those (at least the formatting issues).

DOCS: clarify meaning of merge_streams option (#664)

---

.github/release.yml
docs/requirements.txt

I see some RTD issues over at https://github.com/executablebooks/MyST-NB/pull/646, so open this small PR to test out and if needed to fix it.
After this PR the auto generated released docs will be cleaner, (~and it also removes an unnecessary deprecation workaround~ it is still required to keep compatibility with sphinx 8.1.3.)

MAINT: minor cleanups

---

docs/quickstart.md

This is the myst-parser part of #622. Ideally this should be fixed in code, but en lieu we should mention it in the docs.

DOC: Mention conflict with myst_parser extension

---

docs/reference/contributing.md

Hi, just a small fix 😊 
Link now points to https://executablebooks.org/en/latest/contribute/

Fix link to EBP Contributing Guide

---

docs/configuration.md
myst_nb/core/config.py
myst_nb/core/render.py
myst_nb/static/mystnb.css
tests/notebooks/scroll_outputs.ipynb
tests/test_render_outputs.py
tests/test_render_outputs/test_scroll_outputs.xml

Fixes #677 
* Introduced a new configuration option `scroll_outputs` in `myst_nb/core/config.py` to enable scrollable long outputs - configurable at global, file, cell, and render levels.
* Updated the `myst_nb/core/render.py` logic to apply the `tag_output_scroll` class to cells when the `scroll_outputs` configuration is enabled.
* Added tests for this config: test case in `test_render_outputs.py`, input notebook `scroll_outputs.ipynb` and output AST `test_scroll_outputs.xml`. This was heavily inspired from [hide_cell_content option PR](https://github.com/executablebooks/MyST-NB/pull/446/files#diff-362105cf18876b3c511844baa054405a6ea93b1a36d1666159d8e36866247b3c).
* [Bonus] Added tags `scroll-output` (or `output_scroll`) and `scroll-input` in documentation (they was no documentation …

Add scroll_outputs configuration
