sphinx_notebook/parser.py

closes https://github.com/ExecutableBookProject/sphinx-notebook/issues/17

fixing parser headings

---

sphinx_notebook/parser.py

closes https://github.com/ExecutableBookProject/sphinx-notebook/issues/18
booyah figured it out, thanks @chrisjsewell for the help

not using document, also fixing widget state

---

README.md
docs/conf.py
docs/index.md

updating docs with some more install instructions

updating docs

---

docs/conf.py
docs/index.md
docs/jupyter_sphinx.md
setup.py
sphinx_notebook/__init__.py
sphinx_notebook/parser.py

For comparison across syntaxes etc, and to see if there are obvious places they overlap.

jupyter sphinx example

---

myst_nb/_static/mystnb.css

this makes the CSS a bit more robust across themes by controlling the within-cell CSS a bit more. Should make it look better in the RTD theme at the least

making css more robust

---

setup.py

Upgrade to new myst-parser version 0.5

---

docs/conf.py
docs/use/index.md
docs/use/markdown.md

Adding a page about markdown and notebooks, cc @jstac

adding markdown notebook page

---

myst_nb/_static/mystnb.css

Add CSS; left green border to input cells

---

docs/conf.py
myst_nb/_static/mystnb.css
setup.py

fixing copybutton CSS and adding selector

---

docs/index.md

pydata-sphinx namechange

---

myst_nb/__init__.py

bump release version

---

docs/develop/contributing.md
docs/develop/index.md
docs/index.md
docstring.fmt.mustache

Add a page on package development, which @jstac can use to fix he's PR #104 😆 
https://267-241268229-gh.circle-artifacts.com/0/html/develop/contributing.html
Also @AakashGfude, perhaps you would like to add a page about writing/running tests, as you have a pretty good understanding of that now 😁

Add development documentation

---

myst_nb/cache.py

The previous implementation fails when an existing notebook is changed with failing code.
For example make the MyST-NB documentation, then add `raise Exception` to a cell in `use/basic.ipynb`, and re-run:
With the new (simplified) code:
@AakashGfude is there any reason why you were trying to find the cache record by URI? (something you really shouldn't be trying to do 😬)

Fix cache outputs retrieval for invalidated notebooks

---

docs/use/basic.md
myst_nb/__init__.py
myst_nb/_static/mystnb.js

This adds the default notebook mathjax config as a little javascript file.
@phaustin @chrisjsewell think this will fix the problem?
closes https://github.com/ExecutableBookProject/MyST-NB/issues/99

adding jupyter notebook mathjax config

---

.github/workflows/tests.yml

Reverts ExecutableBookProject/MyST-NB#150

Revert "github action conditions"

---

myst_nb/__init__.py
setup.py

Idea came from spatialaudio/nbsphinx#440

Exclude `.ipynb_checkpoints` by default

---

docs/develop/contributing.md

closes https://github.com/ExecutableBookProject/MyST-NB/issues/161

release instructions

---

myst_nb/transform.py

This adds support for the linkcheck builder, to ensure that `make linkcheck` will complete without erroring

linkcheck builder

---

myst_nb/transform.py
setup.py

jupyter sphinx released 0.2.4 so this bumps to use that as it's a stable version. will also make a release if this works so that jupyter book gets the same update

bumping jupyter sphinx

---

myst_nb/__init__.py
tests/notebooks/with_glue.ipynb
tests/test_glue/test_parser.xml

this also adds a glue title in the tests to make sure that it will pass as expected
closes https://github.com/executablebooks/MyST-NB/issues/170

registering glue nodes

---

docs/develop/index.md
docs/index.md

adding badges to docs

---

myst_nb/__init__.py
myst_nb/cache.py
myst_nb/parser.py
tests/notebooks/complex_outputs_unrun_timeout.ipynb
tests/test_execute.py

**NOTE**:-  This PR should only be merged after this one https://github.com/ExecutableBookProject/jupyter-cache/pull/48
Hey @chrisjsewell , should we give a timeout of -1 like this? because a few notebooks where failing with timeout error. Or do we want to control its value from somewhere?

adding a timeout for execution

---

docs/use/execute.md

showing execution errors

---

docs/index.md
myst_nb/__init__.py
tests/nb_fixtures/basic.txt

activating the post transform from the myst parser to resolve references
also adds an example of this usage in the docs so we know it works

using myst post xform for references

---

README.md

Fixed a dead link in the README

Fix typo on myst parser link

---

myst_nb/__init__.py
myst_nb/cache.py
myst_nb/converter.py
myst_nb/parser.py
tests/test_execute.py
tests/test_text_based.py

- Add more signature typing and docstrings
- Move config value validation to seperate function
- Rename functions in cache.py and improve their logical flow
- Rename variable stored in sphinx environment, to share same suffix:
- `path_to_cache` -> `nb_path_to_cache`
- `allowed_nb_exec_suffixes` -> `nb_allowed_exec_suffixes`
- `excluded_nb_exec_paths` -> `nb_excluded_exec_paths`

♻️ REFACTOR: Improve code base

---

CHANGELOG.md
myst_nb/__init__.py
setup.py

To ensure a few new features and bug fixes are incorporated

⬆️ UPGRADE: myst-parser patch version

---

CHANGELOG.md
docs/conf.py
docs/examples/custom-formats.Rmd
docs/examples/interactive.md
docs/use/markdown.md
myst_nb/__init__.py
myst_nb/execution.py
myst_nb/nb_glue/domain.py
myst_nb/nodes.py
myst_nb/render_outputs.py
setup.py
tests/nb_fixtures/basic.txt
tox.ini

⬆️ UPGRADE: myst-parser v0.12.9

---

setup.py

- I just noticed that homepage link did not work.  I think the change
is self-explinatory and navigating to the web to fill a possible PR
template isn't worth the time.
- Review: none probably necessary

MAINTAIN: Fix homepage link

---

docs/conf.py

This fixes some configuration that was throwing an error in the docs

MAINTAIN: fixing docs build

---

README.md
docs/reference/contributing.md

Minor typo fix while I'm hunting for a possible bug.

📚 DOCS: Fix link in README

---

myst_nb/sphinx_ext.py

by adding to sphinx builds with file named with content hash

👌 IMPROVE: cache bust changes to CSS

---

.github/workflows/tests.yml

Fixes the codecov job in our tests workflow.

ci: use codecov v3 action

---

docs/render/hiding.md

I never used cell tags before and after some googling I found this tutorial. Maybe other people might find this link useful as well.

Add note about how to use cell tags

---

docs/conf.py
myst_nb/cli.py
myst_nb/core/config.py
myst_nb/core/execute/base.py
myst_nb/core/execute/cache.py
myst_nb/core/execute/direct.py
myst_nb/core/execute/inline.py
myst_nb/core/lexers.py
myst_nb/core/loggers.py
myst_nb/core/read.py
myst_nb/core/render.py
myst_nb/core/variables.py
myst_nb/docutils_.py
myst_nb/ext/download.py
myst_nb/ext/eval/__init__.py
myst_nb/ext/execution_tables.py
myst_nb/ext/glue/__init__.py
myst_nb/ext/glue/crossref.py
myst_nb/ext/glue/directives.py
myst_nb/ext/glue/roles.py
myst_nb/ext/glue/utils.py
myst_nb/sphinx_.py
myst_nb/sphinx_ext.py
myst_nb/warnings_.py
pyproject.toml
tests/conftest.py
tests/test_codecell_file.py
tests/test_execute.py
tests/test_parser.py
tests/test_text_based.py

This larger limit was supposed to be for flake8 only

MAINT: restore default line length

---

myst_nb/__init__.py

MAINT: bump version

---

CHANGELOG.md

Populating the changelog file from the release notes

DOC: adding changelog for 1.1.0 and 1.1.1
